/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.intranet.views;

import ArrayListStudents.AcumulacionEstudiantes;
import com.intranet.models.Estudiante;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class ListStudents extends javax.swing.JFrame {
    DefaultTableModel modelo;
    Estudiante estudiante;
    AcumulacionEstudiantes mantEstudiante;
    public ListStudents() {
        initComponents();
        

        panelTitulos1.setVisible(false);
        panelEstudiantes2.setVisible(false);
        panelTitulos2.setVisible(false);
        panelEstudiantes3.setVisible(false);
        panelTitulos3.setVisible(false);
        panelEstudiantes4.setVisible(false);
        panelTitulos4.setVisible(false);
        panelEstudiantes5.setVisible(false);
        panelTitulos5.setVisible(false);
        panelEstudiantes6.setVisible(false);
        panelTitulos6.setVisible(false);
        

        String[] columnas={"Nombre Completo","Correo ","Seccion"};
        modelo = new DefaultTableModel(columnas,0);
        tbEstudiante1.setModel(modelo);
        mantEstudiante=new AcumulacionEstudiantes();
        
        jScrollPane1.setVisible(false);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelEstudiantes6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnGrado2 = new javax.swing.JButton();
        panelTitulos1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnGrado3 = new javax.swing.JButton();
        panelTitulos2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnGrado4 = new javax.swing.JButton();
        btnGrado5 = new javax.swing.JButton();
        btnGrado6 = new javax.swing.JButton();
        btnGrado1 = new javax.swing.JButton();
        panelTitulos3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        panelTitulos4 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        panelTitulos5 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        panelEstudiantes2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        panelEstudiantes3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        panelEstudiantes4 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        panelTitulos6 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        panelEstudiantes5 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEstudiante1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 730));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelEstudiantes6.setBackground(new java.awt.Color(255, 255, 255));
        panelEstudiantes6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("A");
        panelEstudiantes6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 30, -1));

        jLabel9.setText("Jose Diefo Aviles Salas");
        panelEstudiantes6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 150, -1));

        jLabel10.setText("SO363009@gmail.com");
        panelEstudiantes6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 130, -1));

        jButton1.setBackground(new java.awt.Color(174, 31, 35));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Dar de baja");
        panelEstudiantes6.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, -1, 20));

        jButton3.setBackground(new java.awt.Color(5, 51, 74));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Editar");
        panelEstudiantes6.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 100, 20));

        jPanel1.add(panelEstudiantes6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 660, 770, 40));

        btnGrado2.setText("2DO GRADO ▼");
        btnGrado2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGrado2.setPreferredSize(new java.awt.Dimension(34, 47));
        btnGrado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrado2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnGrado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 770, 40));

        panelTitulos1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Nombres y Apellidos");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Correo Institucional");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Secciones");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Configuraciones");

        javax.swing.GroupLayout panelTitulos1Layout = new javax.swing.GroupLayout(panelTitulos1);
        panelTitulos1.setLayout(panelTitulos1Layout);
        panelTitulos1Layout.setHorizontalGroup(
            panelTitulos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitulos1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel4)
                .addGap(74, 74, 74)
                .addComponent(jLabel5)
                .addGap(89, 89, 89)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(52, 52, 52))
        );
        panelTitulos1Layout.setVerticalGroup(
            panelTitulos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTitulos1Layout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addGroup(panelTitulos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)))
        );

        jPanel1.add(panelTitulos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 770, 20));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setPreferredSize(new java.awt.Dimension(220, 720));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 218, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel8.setText("LISTA ESTUDIANTES");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        btnGrado3.setText("3ER GRADO ▼");
        btnGrado3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGrado3.setPreferredSize(new java.awt.Dimension(34, 47));
        btnGrado3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrado3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnGrado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 770, 40));

        panelTitulos2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Nombres y Apellidos");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Correo Institucional");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Secciones");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Configuraciones");

        javax.swing.GroupLayout panelTitulos2Layout = new javax.swing.GroupLayout(panelTitulos2);
        panelTitulos2.setLayout(panelTitulos2Layout);
        panelTitulos2Layout.setHorizontalGroup(
            panelTitulos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitulos2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel11)
                .addGap(74, 74, 74)
                .addComponent(jLabel12)
                .addGap(89, 89, 89)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(52, 52, 52))
        );
        panelTitulos2Layout.setVerticalGroup(
            panelTitulos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTitulos2Layout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addGroup(panelTitulos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)))
        );

        jPanel1.add(panelTitulos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, -1, -1));

        btnGrado4.setText("4TO GRADO ▼");
        btnGrado4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGrado4.setPreferredSize(new java.awt.Dimension(34, 47));
        btnGrado4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrado4ActionPerformed(evt);
            }
        });
        jPanel1.add(btnGrado4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 770, 40));

        btnGrado5.setText("5TO GRADO ▼");
        btnGrado5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGrado5.setPreferredSize(new java.awt.Dimension(34, 47));
        btnGrado5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrado5ActionPerformed(evt);
            }
        });
        jPanel1.add(btnGrado5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 770, 40));

        btnGrado6.setText("6TO GRADO ▼");
        btnGrado6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGrado6.setPreferredSize(new java.awt.Dimension(34, 47));
        btnGrado6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrado6ActionPerformed(evt);
            }
        });
        jPanel1.add(btnGrado6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 590, 770, 40));

        btnGrado1.setText("1ER GRADO ▼");
        btnGrado1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGrado1.setPreferredSize(new java.awt.Dimension(34, 47));
        btnGrado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrado1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnGrado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 770, 40));

        panelTitulos3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Nombres y Apellidos");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Correo Institucional");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Secciones");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setText("Configuraciones");

        javax.swing.GroupLayout panelTitulos3Layout = new javax.swing.GroupLayout(panelTitulos3);
        panelTitulos3.setLayout(panelTitulos3Layout);
        panelTitulos3Layout.setHorizontalGroup(
            panelTitulos3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitulos3Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel18)
                .addGap(74, 74, 74)
                .addComponent(jLabel19)
                .addGap(89, 89, 89)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(52, 52, 52))
        );
        panelTitulos3Layout.setVerticalGroup(
            panelTitulos3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTitulos3Layout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addGroup(panelTitulos3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)))
        );

        jPanel1.add(panelTitulos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, -1, -1));

        panelTitulos4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setText("Nombres y Apellidos");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setText("Correo Institucional");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setText("Secciones");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setText("Configuraciones");

        javax.swing.GroupLayout panelTitulos4Layout = new javax.swing.GroupLayout(panelTitulos4);
        panelTitulos4.setLayout(panelTitulos4Layout);
        panelTitulos4Layout.setHorizontalGroup(
            panelTitulos4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitulos4Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel22)
                .addGap(74, 74, 74)
                .addComponent(jLabel23)
                .addGap(89, 89, 89)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addGap(52, 52, 52))
        );
        panelTitulos4Layout.setVerticalGroup(
            panelTitulos4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTitulos4Layout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addGroup(panelTitulos4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)))
        );

        jPanel1.add(panelTitulos4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, -1, -1));

        panelTitulos5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setText("Nombres y Apellidos");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setText("Correo Institucional");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel28.setText("Secciones");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel29.setText("Configuraciones");

        javax.swing.GroupLayout panelTitulos5Layout = new javax.swing.GroupLayout(panelTitulos5);
        panelTitulos5.setLayout(panelTitulos5Layout);
        panelTitulos5Layout.setHorizontalGroup(
            panelTitulos5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitulos5Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel26)
                .addGap(74, 74, 74)
                .addComponent(jLabel27)
                .addGap(89, 89, 89)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addGap(52, 52, 52))
        );
        panelTitulos5Layout.setVerticalGroup(
            panelTitulos5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTitulos5Layout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addGroup(panelTitulos5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)))
        );

        jPanel1.add(panelTitulos5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 520, -1, -1));

        panelEstudiantes2.setBackground(new java.awt.Color(255, 255, 255));
        panelEstudiantes2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("A");
        panelEstudiantes2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 30, -1));

        jLabel30.setText("Jose Diefo Aviles Salas");
        panelEstudiantes2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 150, -1));

        jLabel31.setText("SO363009@gmail.com");
        panelEstudiantes2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 130, -1));

        jButton5.setBackground(new java.awt.Color(174, 31, 35));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Dar de baja");
        panelEstudiantes2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, -1, 20));

        jButton6.setBackground(new java.awt.Color(5, 51, 74));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Editar");
        panelEstudiantes2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 100, 20));

        jPanel1.add(panelEstudiantes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 770, 40));

        panelEstudiantes3.setBackground(new java.awt.Color(255, 255, 255));
        panelEstudiantes3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("A");
        panelEstudiantes3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 30, -1));

        jLabel32.setText("Jose Diefo Aviles Salas");
        panelEstudiantes3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 150, -1));

        jLabel33.setText("SO363009@gmail.com");
        panelEstudiantes3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 130, -1));

        jButton7.setBackground(new java.awt.Color(174, 31, 35));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Dar de baja");
        panelEstudiantes3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, -1, 20));

        jButton8.setBackground(new java.awt.Color(5, 51, 74));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Editar");
        panelEstudiantes3.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 100, 20));

        jPanel1.add(panelEstudiantes3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 770, 40));

        panelEstudiantes4.setBackground(new java.awt.Color(255, 255, 255));
        panelEstudiantes4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setText("A");
        panelEstudiantes4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 30, -1));

        jLabel35.setText("Jose Diefo Aviles Salas");
        panelEstudiantes4.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 150, -1));

        jLabel36.setText("SO363009@gmail.com");
        panelEstudiantes4.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 130, -1));

        jButton9.setBackground(new java.awt.Color(174, 31, 35));
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Dar de baja");
        panelEstudiantes4.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, -1, 20));

        jButton10.setBackground(new java.awt.Color(5, 51, 74));
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Editar");
        panelEstudiantes4.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 100, 20));

        jPanel1.add(panelEstudiantes4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 770, 40));

        panelTitulos6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel37.setText("Nombres y Apellidos");

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel38.setText("Correo Institucional");

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel39.setText("Secciones");

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel40.setText("Configuraciones");

        javax.swing.GroupLayout panelTitulos6Layout = new javax.swing.GroupLayout(panelTitulos6);
        panelTitulos6.setLayout(panelTitulos6Layout);
        panelTitulos6Layout.setHorizontalGroup(
            panelTitulos6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitulos6Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel37)
                .addGap(74, 74, 74)
                .addComponent(jLabel38)
                .addGap(89, 89, 89)
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(jLabel40)
                .addGap(52, 52, 52))
        );
        panelTitulos6Layout.setVerticalGroup(
            panelTitulos6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTitulos6Layout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addGroup(panelTitulos6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(jLabel38)
                    .addComponent(jLabel39)
                    .addComponent(jLabel40)))
        );

        jPanel1.add(panelTitulos6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 630, -1, -1));

        panelEstudiantes5.setBackground(new java.awt.Color(255, 255, 255));
        panelEstudiantes5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setText("A");
        panelEstudiantes5.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 30, -1));

        jLabel42.setText("Jose Diefo Aviles Salas");
        panelEstudiantes5.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 150, -1));

        jLabel43.setText("SO363009@gmail.com");
        panelEstudiantes5.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 130, -1));

        jButton11.setBackground(new java.awt.Color(174, 31, 35));
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Dar de baja");
        panelEstudiantes5.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, -1, 20));

        jButton12.setBackground(new java.awt.Color(5, 51, 74));
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Editar");
        panelEstudiantes5.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 100, 20));

        jPanel1.add(panelEstudiantes5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 550, 770, 40));

        tbEstudiante1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbEstudiante1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 330, 60));

        jButton4.setBackground(new java.awt.Color(5, 51, 74));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Editar");
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 30, 100, 20));

        jButton2.setBackground(new java.awt.Color(174, 31, 35));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Dar de baja");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 30, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1094, 738));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGrado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrado2ActionPerformed
       
       boolean visible2 = panelEstudiantes2.isVisible();
       panelEstudiantes2.setVisible(!visible2);
       boolean visibleB = panelTitulos2.isVisible();
       panelTitulos2.setVisible(!visibleB);
       
       if (visible2 && visibleB) {
           btnGrado2.setText("2DO GRADO ▶");
        } else {
           btnGrado2.setText("2DO GRADO ▼");
        }

    }//GEN-LAST:event_btnGrado2ActionPerformed

    private void btnGrado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrado1ActionPerformed
    
       boolean visibleA = jScrollPane1.isVisible();
       jScrollPane1.setVisible(!visibleA);
       
       if (visibleA) {
           btnGrado1.setText("1ERO GRADO ▶");
        } else {
           btnGrado1.setText("1ERO GRADO ▼");
           mostrarTabla();
        }
        
        
     
     
    }//GEN-LAST:event_btnGrado1ActionPerformed
            
    private void mostrarTabla(){
        modelo.setRowCount(0);
        ArrayList<Estudiante> lista=mantEstudiante.obtenerEstudiante();
        for (Estudiante el : lista) {
            Object[] fila={el.getNombEstu(),
                           el.getCorreoEstu(),
                           el.getGrado(),
            };
            modelo.addRow(fila);
        }
    }
    private void btnGrado3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrado3ActionPerformed
        boolean visible3 = panelEstudiantes3.isVisible();
        panelEstudiantes3.setVisible(!visible3);
        boolean visibleC = panelTitulos3.isVisible();
        panelTitulos3.setVisible(!visibleC);

        if (visible3 && visibleC) {
            btnGrado3.setText("3ER GRADO ▶");
        } else {
            btnGrado3.setText("3ER GRADO ▼");
        }

    }//GEN-LAST:event_btnGrado3ActionPerformed
      
    private void btnGrado4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrado4ActionPerformed
        boolean visible4 = panelEstudiantes4.isVisible();
        panelEstudiantes4.setVisible(!visible4);
        boolean visibleD = panelTitulos4.isVisible();
        panelTitulos4.setVisible(!visibleD);

        if (visible4 && visibleD) {
            btnGrado4.setText("4TO GRADO ▶");
        } else {
            btnGrado4.setText("4TO GRADO ▼");
        }
    }//GEN-LAST:event_btnGrado4ActionPerformed

    private void btnGrado5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrado5ActionPerformed
        boolean visible5 = panelEstudiantes5.isVisible();
        panelEstudiantes5.setVisible(!visible5);
        boolean visibleE = panelTitulos5.isVisible();
        panelTitulos5.setVisible(!visibleE);

        if (visible5 && visibleE) {
            btnGrado5.setText("5TO GRADO ▶");
        } else {
            btnGrado5.setText("5TO GRADO ▼");
        }
    }//GEN-LAST:event_btnGrado5ActionPerformed

    private void btnGrado6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrado6ActionPerformed
        boolean visible6 = panelEstudiantes6.isVisible();
        panelEstudiantes6.setVisible(!visible6);
        boolean visibleF = panelTitulos6.isVisible();
        panelTitulos6.setVisible(!visibleF);

        if (visible6 && visibleF) {
            btnGrado6.setText("6TO GRADO ▶");
        } else {
            btnGrado6.setText("6TO GRADO ▼");
        }
    }//GEN-LAST:event_btnGrado6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      int filaSeleccionada=tbEstudiante1.getSelectedRow();
      
      if(filaSeleccionada==-1){
          JOptionPane.showMessageDialog(this, "Por favor seleccine una fila","Advertencia",JOptionPane.WARNING_MESSAGE);
          
      } else {
          mantEstudiante.elimanrEstudiante(filaSeleccionada);
          
          JOptionPane.showMessageDialog(this, "Se elimino correctamente");
          mostrarTabla();
      }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListStudents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGrado1;
    private javax.swing.JButton btnGrado2;
    private javax.swing.JButton btnGrado3;
    private javax.swing.JButton btnGrado4;
    private javax.swing.JButton btnGrado5;
    private javax.swing.JButton btnGrado6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelEstudiantes2;
    private javax.swing.JPanel panelEstudiantes3;
    private javax.swing.JPanel panelEstudiantes4;
    private javax.swing.JPanel panelEstudiantes5;
    private javax.swing.JPanel panelEstudiantes6;
    private javax.swing.JPanel panelTitulos1;
    private javax.swing.JPanel panelTitulos2;
    private javax.swing.JPanel panelTitulos3;
    private javax.swing.JPanel panelTitulos4;
    private javax.swing.JPanel panelTitulos5;
    private javax.swing.JPanel panelTitulos6;
    private javax.swing.JTable tbEstudiante1;
    // End of variables declaration//GEN-END:variables
}
