/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.intranet.views;

import com.intranet.components.Sidebar;
import com.intranet.utils.AlertUtils;
import com.intranet.utils.Validador;


/**
 *
 * @author USUARIO
 */
public class RegisterStudents extends javax.swing.JFrame {

    /**
     * Creates new form RegisterStudents
     */
    public RegisterStudents() {
        initComponents();
        Sidebar sidebar = new Sidebar();
        this.add(sidebar );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtDNIEstudiante = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFijoEstudiante = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFechaEstudiante = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNombreEstudiante = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtProvinciaEstudiante = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCorreoEstudiante = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtCelularEstudiante = new javax.swing.JTextField();
        txtDistritoEstudiante = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtDepartamentoEstudiante = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtDireccionEstudiante = new javax.swing.JTextField();
        cbGradoEstudiante = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreApoderado = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCelularApoderado = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtDNIApoderado = new javax.swing.JTextField();
        btnRegistrarEstudiante = new javax.swing.JButton();
        btnListaEstudiante = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("REGISTRO DE ESTUDANTES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 269, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos del estudiante", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(740, 380));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Nro DNI:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, -1, -1));
        jPanel3.add(txtDNIEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 120, -1));

        jLabel4.setText("Teléfono Fijo:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, -1, -1));
        jPanel3.add(txtFijoEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 120, -1));

        jLabel5.setText("Fecha de Nacimiento:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, -1));
        jPanel3.add(txtFechaEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 150, -1));

        jLabel6.setText("Nombre Completo:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));
        jPanel3.add(txtNombreEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 270, -1));

        jLabel7.setText("Grado:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, -1, -1));

        jLabel8.setText("Provincia:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));
        jPanel3.add(txtProvinciaEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 120, -1));

        jLabel10.setText("Correo Personal:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));
        jPanel3.add(txtCorreoEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 270, -1));

        jLabel11.setText("Teléfono Celular:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, -1, -1));

        jLabel13.setText("Distrito:");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, -1));
        jPanel3.add(txtCelularEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 150, -1));
        jPanel3.add(txtDistritoEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 140, -1));

        jLabel14.setText("Departamento:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));
        jPanel3.add(txtDepartamentoEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 150, -1));

        jLabel15.setText("Dirección:");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));
        jPanel3.add(txtDireccionEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 450, -1));

        cbGradoEstudiante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Seleccione una opción---", "1", "2", "3" }));
        jPanel3.add(cbGradoEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, 340));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos del apoderado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(670, 121));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nombre Completo:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));
        jPanel2.add(txtNombreApoderado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 280, -1));

        jLabel12.setText("Teléfono Celular:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, -1));
        jPanel2.add(txtCelularApoderado, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 150, -1));

        jLabel16.setText("Nro DNI:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, -1, -1));
        jPanel2.add(txtDNIApoderado, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 130, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 740, -1));

        btnRegistrarEstudiante.setBackground(new java.awt.Color(180, 0, 35));
        btnRegistrarEstudiante.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrarEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarEstudiante.setText("REGISTRAR ESTUDIANTE");
        btnRegistrarEstudiante.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        btnRegistrarEstudiante.setPreferredSize(new java.awt.Dimension(320, 40));
        btnRegistrarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarEstudianteActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 610, 280, 49));

        btnListaEstudiante.setBackground(new java.awt.Color(180, 0, 35));
        btnListaEstudiante.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnListaEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        btnListaEstudiante.setText("LISTA DE ESTUDIANTES");
        jPanel1.add(btnListaEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 610, 280, 49));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1094, 728));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarEstudianteActionPerformed
        String nombreEstudiante = txtNombreEstudiante.getText();
        String fecha = txtFechaEstudiante.getText();
        String dniEstudiante = txtDNIEstudiante.getText();
        String correoEstudiante = txtCorreoEstudiante.getText();
        String celularEstudiante = txtCelularEstudiante.getText();
        String fijo = txtFijoEstudiante.getText();
        String departamento = txtDepartamentoEstudiante.getText();
        String provincia = txtProvinciaEstudiante.getText();
        String distrito = txtDistritoEstudiante.getText();
        String direccion = txtDireccionEstudiante.getText();
        String grado = cbGradoEstudiante.getSelectedItem().toString();
        String nombreApoderado = txtNombreApoderado.getText();
        String celularApoderado = txtCelularApoderado.getText();
        String dniApoderado = txtDNIApoderado.getText();
        
        // Validacion de campos generales
        if (nombreEstudiante.isEmpty() || fecha.isEmpty() ||  dniEstudiante.isEmpty() ||  correoEstudiante.isEmpty() || 
                celularEstudiante.isEmpty() ||  fijo.isEmpty() ||  departamento.isEmpty() ||  provincia.isEmpty() ||  
                distrito.isEmpty()||  direccion.isEmpty() ||  grado.isEmpty() ||  nombreApoderado.isEmpty()|| 
                celularApoderado.isEmpty() ||  dniApoderado.isEmpty()) {
        
            AlertUtils.showWarning("Todos los campos son obligatorios");
            return;
        } 
        
        // Validación de campos individuales
        String resultadoCorreo = Validador.esCorreoValido(correoEstudiante);
        if (!resultadoCorreo.equals("OK")) {
            AlertUtils.showWarning(resultadoCorreo);
            return;
        } 
        
        
       
    }//GEN-LAST:event_btnRegistrarEstudianteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterStudents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListaEstudiante;
    private javax.swing.JButton btnRegistrarEstudiante;
    private javax.swing.JComboBox<String> cbGradoEstudiante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtCelularApoderado;
    private javax.swing.JTextField txtCelularEstudiante;
    private javax.swing.JTextField txtCorreoEstudiante;
    private javax.swing.JTextField txtDNIApoderado;
    private javax.swing.JTextField txtDNIEstudiante;
    private javax.swing.JTextField txtDepartamentoEstudiante;
    private javax.swing.JTextField txtDireccionEstudiante;
    private javax.swing.JTextField txtDistritoEstudiante;
    private javax.swing.JTextField txtFechaEstudiante;
    private javax.swing.JTextField txtFijoEstudiante;
    private javax.swing.JTextField txtNombreApoderado;
    private javax.swing.JTextField txtNombreEstudiante;
    private javax.swing.JTextField txtProvinciaEstudiante;
    // End of variables declaration//GEN-END:variables
}
