/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.intranet.views;

import com.intranet.utils.AlertUtils;
import com.intranet.utils.Validador;

/**
 *
 * @author USUARIO
 */
public class RegisterTeachers extends javax.swing.JFrame {

    /**
     * Creates new form RegisterTeachers
     */
    public RegisterTeachers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtDNIDocente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFechaDocente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNombreDocente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtProvinciaDocente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCorreoDocente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtCelularDocente = new javax.swing.JTextField();
        txtDistritoDocente = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtDepartamentoDocente = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtOcupacionDocente = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRegistrarDocente = new javax.swing.JButton();
        btnListaDocentes = new javax.swing.JButton();
        btnImagen = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 720));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos del docente", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(740, 380));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Nro DNI:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, -1));
        jPanel3.add(txtDNIDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 130, -1));

        jLabel5.setText("Fecha de Nacimiento:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, -1));
        jPanel3.add(txtFechaDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 150, -1));

        jLabel6.setText("Nombre Completo:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));
        jPanel3.add(txtNombreDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 270, -1));

        jLabel8.setText("Provincia:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));
        jPanel3.add(txtProvinciaDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 120, -1));

        jLabel10.setText("Correo Personal:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));
        jPanel3.add(txtCorreoDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 270, -1));

        jLabel11.setText("Teléfono Celular:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, -1, -1));

        jLabel13.setText("Distrito:");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));
        jPanel3.add(txtCelularDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 150, -1));
        jPanel3.add(txtDistritoDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 120, -1));

        jLabel14.setText("Departamento:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));
        jPanel3.add(txtDepartamentoDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 150, -1));

        jLabel15.setText("Ocupación:");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));
        jPanel3.add(txtOcupacionDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 150, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 140, 140));

        jLabel1.setText("Ingrese una foto de perfil:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 140, -1));

        btnRegistrarDocente.setBackground(new java.awt.Color(180, 0, 35));
        btnRegistrarDocente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrarDocente.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarDocente.setText("REGISTRAR DOCENTE");
        btnRegistrarDocente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        btnRegistrarDocente.setPreferredSize(new java.awt.Dimension(320, 40));
        btnRegistrarDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarDocenteActionPerformed(evt);
            }
        });
        jPanel3.add(btnRegistrarDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 280, 49));

        btnListaDocentes.setBackground(new java.awt.Color(180, 0, 35));
        btnListaDocentes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnListaDocentes.setForeground(new java.awt.Color(255, 255, 255));
        btnListaDocentes.setText("LISTA DE DOCENTES");
        jPanel3.add(btnListaDocentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, 280, 49));

        btnImagen.setBackground(new java.awt.Color(5, 51, 74));
        btnImagen.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnImagen.setForeground(new java.awt.Color(255, 255, 255));
        btnImagen.setText("Subir archivo");
        jPanel3.add(btnImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 100, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setText("REGISTRO DE DOCENTES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(245, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addGap(49, 49, 49)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1094, 728));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarDocenteActionPerformed
        String nombreDocente= txtNombreDocente.getText();
        String fecha = txtFechaDocente.getText();
        String dniDocente = txtDNIDocente.getText();
        String correoDocente = txtCorreoDocente.getText();
        String celularDocente = txtCelularDocente.getText();
        String departamento = txtDepartamentoDocente.getText();
        String provincia = txtProvinciaDocente.getText();
        String distrito = txtDistritoDocente.getText();
        String ocupacion = txtOcupacionDocente.getText();


        // Validacion de campos generales
        if (nombreDocente.isEmpty() || fecha.isEmpty() ||  dniDocente.isEmpty() ||  correoDocente.isEmpty() ||
            celularDocente.isEmpty() ||  departamento.isEmpty() ||  provincia.isEmpty() || ocupacion.isEmpty() ||
            distrito.isEmpty()) {

            AlertUtils.showWarning("Todos los campos son obligatorios");
            return;
        }

        // Validación de campos individuales
        String resultadoCorreo = Validador.esCorreoValido(correoDocente);
        if (!resultadoCorreo.equals("OK")) {
            AlertUtils.showWarning(resultadoCorreo);
            return;
        }

    }//GEN-LAST:event_btnRegistrarDocenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterTeachers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterTeachers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterTeachers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterTeachers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterTeachers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImagen;
    private javax.swing.JButton btnListaDocentes;
    private javax.swing.JButton btnRegistrarDocente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtCelularDocente;
    private javax.swing.JTextField txtCorreoDocente;
    private javax.swing.JTextField txtDNIDocente;
    private javax.swing.JTextField txtDepartamentoDocente;
    private javax.swing.JTextField txtDistritoDocente;
    private javax.swing.JTextField txtFechaDocente;
    private javax.swing.JTextField txtNombreDocente;
    private javax.swing.JTextField txtOcupacionDocente;
    private javax.swing.JTextField txtProvinciaDocente;
    // End of variables declaration//GEN-END:variables
}
